language: android
sudo: false
android:
  components:
  - tools
  - build-tools-25.0.2
  - platform-tools
  - extra-android-m2repository
  - extra-google-android-support
  - android-25
  - sys-img-armeabi-v7a-android-25
jdk: oraclejdk8
os:
- linux
notifications:
  email: true
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: releases
  api_key:
    secure: t10r5KEQWqWD6P6fB93JCLofVvH1/fWJ9UgVIb2sC5ICT0QpiA9+4PSXJVia/49m5Z4Q7v6Y8nTuM/KvoDMlY5Aa3e8gmtOK6Qx9aY0NpU71S07WhtQ8IWTWazG01y9TF5W1zPF853yy0aHzgvteiBBW02w2FYznIXCKqMMNTlm9KOYWp//gp+d6s5YFjar7ZtCYidw2UoCHrjxb/U+banH66qyxXj9a/PMzvo3hh4j8LDiYZ61i/nbnuNhwTyAA8kb1dFz6KQDQYY0pdu5nArAkSzd8UZ09QXWkeEgGbN9sG+n9eGAANqPLUxDb1J8LtYGBPFWGLAWZhGI/N+uaZkw05GchSH7895aMwHBDV0yrLmrB3w9syEQThm2TUwayb7yvXEBJngFVLRymo09bf76sO4SE5DqDCyCcIhFVSXIrnhhbnwjNkwMLzjEdJN0gGY6P4RS6dZtSwg81tp9BitQiSct89vT3jfmmz+6Wi4ptU8bmRuXGhY0bUwk+ucWD7U6dciBxyiiXAlp18nkE3OXswMPsI3RWHn6uBsGcgoYclmXnwOq12PT3p/D4Cceq+u3c4HlgM5POxP+DKHnuen19R1YBI/ZNu1lMbgu9Hu3ipsaBefcScGAZEl8am/eW/9N87adGh4xW+Gsk/9gS1Fe0ZXMvdQcxVolMxJ1ULts=
  file: HTTPPlugin/build/outputs/apk/HTTPPlugin*release*.apk
  skip_cleanup: "true"
  on:
    repo: sebastiankutschbach/HTTPPlugin
    branch: multipleProfiles

after_success:
-sh set_tags.sh
